[project]
name = "llm-toolkit"
version = "0.1.0"
description = "This repo contains all the basic elements to construct effective LLM tasks."
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "adalflow>=0.2.6",
    "google-genai>=0.4.0",
    "loguru>=0.7.3",
    "ollama>=0.4.5",
    "pathlib>=1.0.1",
]
