default_provider: "google"

providers:
  anthropic:
    name: "Anthropic"
    base_url: "https://api.anthropic.com"
    api_version: "2023-06-01"
    default_model: "claude-3-sonnet"
    models:
      claude-3-sonnet:
        name: "claude-3-sonnet-20240229"
        max_tokens: 4096
        temperature: 0.7
      claude-3-haiku:
        name: "claude-3-haiku-20240307"
        max_tokens: 4096
        temperature: 0.7
        timeout: 20
    rate_limits:
      requests_per_minute: 1000
      tokens_per_minute: 80000

  google:
    name: "Google"
    base_url: ""
    default_model: "gemini-flash"
    models:
      gemini-flash:
        name: "gemini-2.5-flash-preview-05-20"
        max_tokens: 128000
        temperature: 0.0
      gemini-pro:
        name: "gemini-pro"
        max_tokens: 128000
        temperature: 0.0

  # TODO: Verify params which are needed
  ollama:
    name: "Ollama"
    base_url: "http://localhost:11434"
    default_model: "llama3.2"
    models:
      llama3.2:
        name: "llama3.2"
        max_tokens: 8192
        options:
          temperature: 0.5
          top_k: 40
        num_predict: 8192
        stream: False